### ISSUE TITLE
start mova error

### ISSUE THREAD

**Issue by halfss** [joshy/mova#1]
Hello，When I run mova, I get this:

[root@i-uantd2en mova]# pwd
/root/mova
[root@i-uantd2en mova]# python3 runserver.py
Traceback (most recent call last):
  File "runserver.py", line 8, in <module>
    from mova.app import app
  File "/root/mova/mova/app.py", line 15, in <module>
    app.config.from_pyfile('config.cfg')
  File "/usr/lib64/python3.4/site-packages/flask/config.py", line 129, in from_pyfile
    with open(filename, mode='rb') as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/root/mova/instance/config.cfg'

can you help this?

**Comment by joshy** [comment]
Hi, 

sure you need a instance folder with a config.cfg file int it. There you should put your instance confiurations. That file is never checked in.

**Comment by halfss** [comment]
thank U, got it
